version: "3.3"

services:
  test_sandbox:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go-example-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
#docker-compose -f docker-compose.yml up  --exit-code-from test_sandbox

#docker-compose -f docker-compose.yml down
